name: ML-Interface CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Pre-commit all files
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools wheel
          python3 -m pip install --upgrade pre-commit

      - name: Check pre-commit
        run: pre-commit run --all-files

  test:
    name: Run unit tests - ${{ matrix.python-version }} | ${{ matrix.os }} ${{ matrix.architecture }}
    needs: lint
    if: always()
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.10.12 ]
        architecture: [ x64 ]
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run all tests using pytest for ML-Interface
        run: |
          python3 -m pytest --cov-report html:cov_html --cov=src tests/

      - name: Upload coverage data to coveralls.io
        if: matrix.python-version == '3.10.12'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m coveralls -v --service=github
